# Generated by Django 5.0 on 2023-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, choices=[('NONE', 'Порода не указана'), ('RUSSIAN_BLUE', 'Русская голубая')], max_length=50),
        ),
        migrations.AddField(
            model_name='cat',
            name='fur',
            field=models.CharField(blank=True, choices=[('LONG', 'Длинная шерсть'), ('MID', 'Средняя длина шерсти'), ('SHORT', 'Коротная длина шерсти')], max_length=50),
        ),
    ]
